# Generated by Django

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    """Initial migration for django_generic_many_to_many_field."""

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericManyToManyRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id_from', models.PositiveIntegerField()),
                ('object_id_to', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generic_relations_from', to='contenttypes.contenttype')),
                ('content_type_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generic_relations_to', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Generic Many-to-Many Relation',
                'verbose_name_plural': 'Generic Many-to-Many Relations',
            },
        ),
        migrations.AddIndex(
            model_name='genericmanytomanyrelation',
            index=models.Index(fields=['content_type_from', 'object_id_from'], name='django_gene_content_idx'),
        ),
        migrations.AddIndex(
            model_name='genericmanytomanyrelation',
            index=models.Index(fields=['content_type_to', 'object_id_to'], name='django_gene_content_to_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='genericmanytomanyrelation',
            unique_together={('content_type_from', 'object_id_from', 'content_type_to', 'object_id_to')},
        ),
    ]
